"""Add image_search_query to plants

Revision ID: 1d76db050b65
Revises: 6b87e7a508bc
Create Date: 2026-03-29 12:53:07.806706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d76db050b65"
down_revision: Union[str, None] = "6b87e7a508bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plants", sa.Column("image_search_query", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plants", "image_search_query")
    # ### end Alembic commands ###
