"""Add user_id to plants and establish relationship

Revision ID: 4daec1def2ff
Revises: 70de6ce5ea6b
Create Date: 2026-03-22 21:45:08.061956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4daec1def2ff"
down_revision: Union[str, None] = "70de6ce5ea6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_plants_user_id"), ["user_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_plants_user_id_users", "users", ["user_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.drop_constraint("fk_plants_user_id_users", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_plants_user_id"))
        batch_op.drop_column("user_id")
    # ### end Alembic commands ###
