"""Add image_url to Plant

Revision ID: 6b87e7a508bc
Revises: 4daec1def2ff
Create Date: 2026-03-22 22:40:05.688372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b87e7a508bc"
down_revision: Union[str, None] = "4daec1def2ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plants", sa.Column("image_url", sa.String(length=1024), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plants", "image_url")
    # ### end Alembic commands ###
