replicaCount: 1

image:
  repository: solid-frontend
  pullPolicy: IfNotPresent
  tag: "prod-local"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik-solid
  annotations: {}
  host: example.com
  tls:
    enabled: true
    secretName: ""
    certResolver: letsencrypt