{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ ternary "websecure" "web" .Values.ingress.tls.enabled | quote }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-api-stripprefix@kubernetescrd,{{ .Release.Namespace }}-api-security-headers@kubernetescrd
    {{- if .Values.ingress.tls.enabled }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- end }}
    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.certResolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.ingress.tls.certResolver | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
      {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-backend-service
            port:
              number: {{ .Values.service.port }}
  {{- if .Values.ingress.monitoring.enabled }}
  - host: {{ .Values.ingress.monitoring.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 80
  {{- end }}
{{- end }}