apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik-solid
  rules:
  - host: backend.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-backend-service
            port:
              number: {{ .Values.service.port }}
  - host: monitoring.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 80
  - host: glitchtip.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: glitchtip-solid-web
            port:
              number: 80