apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "backend-service.fullname" . }}-data
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
