{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-service.databaseSecretName" . }}
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.existingSecretKey }}: {{ .Values.database.url | quote }}
{{- end }}
---
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-service.authSecretName" . }}
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.auth.jwtSecretKey | quote }}
  SESSION_SECRET_KEY: {{ .Values.auth.sessionSecretKey | quote }}
  {{- if .Values.auth.gcpClientId }}
  GCP_CLIENT_ID: {{ .Values.auth.gcpClientId | quote }}
  {{- end }}
  {{- if .Values.auth.gcpClientSecret }}
  GCP_CLIENT_SECRET: {{ .Values.auth.gcpClientSecret | quote }}
  {{- end }}
  {{- if .Values.auth.adminEmail }}
  ADMIN_EMAIL: {{ .Values.auth.adminEmail | quote }}
  {{- end }}
  {{- if .Values.auth.gemApiKey }}
  GEM_API_KEY: {{ .Values.auth.gemApiKey | quote }}
  {{- end }}
{{- end }}