{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-service.databaseSecretName" . }}
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.existingSecretKey }}: {{ .Values.database.url | quote }}
{{- end }}